_BASE_: "Base-FSOD-C4.yaml"
MODEL:
  WEIGHTS: "./output/fsod/meta_training_coco_resnet101_stage_3/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  BACKBONE:
    FREEZE_AT: 5
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.0
  ROI_BOX_HEAD:
    GAMMA_NUM: 2
  RPN:
    PRE_NMS_TOPK_TEST: 12000
    POST_NMS_TOPK_TEST: 100
  FEWX_BASELINE: False
  WITH_ALIGNMENT: True
DATASETS:
  TRAIN: ("coco_2014_train_full_3_shot",)
  TEST: ("coco_2014_val",)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.001
  STEPS: (2000, 3000)
  MAX_ITER: 3000
  WARMUP_ITERS: 200
  CHECKPOINT_PERIOD: 3000
INPUT:
  FS:
    FEW_SHOT: True
    SUPPORT_WAY: 5
    SUPPORT_SHOT: 3
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
OUTPUT_DIR: './output/fsod/finetune_dir/3shot_finetune_coco_resnet101'
TEST:
  EVAL_PERIOD: 3000
