_BASE_: "Base-FSOD-C4.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  BACKBONE:
    FREEZE_AT: 2
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.0
  RPN:
    PRE_NMS_TOPK_TEST: 12000
    POST_NMS_TOPK_TEST: 100
  FEWX_BASELINE: True
  WITH_ALIGNMENT: False
OUTPUT_DIR: './output/fsod/meta_training_coco_resnet101_stage_1'
DATASETS:
  TRAIN: ("coco_2014_train_nonvoc",) 
  TEST: ("coco_2014_val",)
  TEST_SHOTS: (1,2,3,5,10,30)
INPUT:
  FS:
    SUPPORT_WAY: 2
    SUPPORT_SHOT: 30
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.002
  STEPS: (30000, 40000)
  MAX_ITER: 40000
  WARMUP_ITERS: 1000
  WARMUP_FACTOR: 0.1
  CHECKPOINT_PERIOD: 40000
  HEAD_LR_FACTOR: 2.0
TEST:
  EVAL_PERIOD: 40000
